name: New Profile
description: Create a new profile (you can find tutorials in the wiki) 
title: "Create Profile for ..."
labels: [Profile]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out some informations about you! Great to have you as part of the #ASK network! Your data will be published on the LEAD page. Here you can find a tutorial to help you in filling out your information: [link](https://github.com/ASKnetCommunity/LEAD/wiki/Tutorial-%22New-Profile%22-(for-ASKnet-Peers)). If you already have a profile which you want to update, please just fill in the info that you want to change/add, and leave everything empty that should stay the same. 
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "your full name"
    validations:
      required: true  

  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload an image for your profile by dragging & dropping into this textarea or clicking on the bottom of this textarea and select your image. 
    validations:
      required: true

  - type: input
    id: country
    attributes:
      label: Country
      description: "In which country are you active?"
      placeholder: "e.g. South Sudan"
    validations:
      required: false
      
  - type: input
    id: region
    attributes:
      label: Region
      description: "In which region are you active? You can add several regions or cities by separating them with commas."
      placeholder: "e.g. Juba, Rhino-Camp, Berlin"
    validations:
      required: false

  - type: input
    id: hub
    attributes:
      label: Hub
      description: "If you are active in a hub, you can indicate here in which"
      placeholder: "Hub Name"
    validations:
      required: false

  - type: input
    id: languages
    attributes:
      label: Languages
      description: "Please state which languages you speak (and at what level)"
      placeholder: "e.g. English (very good)"
    validations:
      required: false

################# Skills #################

  - type: markdown
    attributes:
      value: |
        ## Skills 
        What are your skills? Please just fill out the fields that apply to you, you can skip the rest and leave it empty. 
        For each skill that you have please enter some evidence, so others can verify what experience you have. That can be: 
        • a degree or a certificate (you don't need to upload it, just type the information)
        • information about a prototype / product you've created (can be a podcast or a video, or a device you've built, or something else, depending on the skill). Feel free to include links. 
        • information about a workshop / training you've conducted
        • a recommendation of an ASKnet member or a former employer
        • any other website where you and your skill is mentioned. 

        Down below you find an open field where you can mention other skills you have, if they are not listed here. 
        
  - type: textarea
    id: Web
    attributes:
      label: Web
      description: e.g. research, using platforms, basic social media experience
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Software
    attributes:
      label: Software
      description: e.g. installing and using different programs, basic coding skills
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Hardware
    attributes:
      label: Hardware
      description: e.g. experience with electronic and/or mechanical devices and hardware
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Community
    attributes:
      label: Community
      description: e.g. community building, connecting people, activism, trauma healing, gender equality awareness
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Organizational_Development
    attributes:
      label: Organizational Development
      description: e.g. entrepreneurship, project management, leading associations, financial literacy etc.
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Media-Art
    attributes:
      label: Media & Art
      description: e.g. audio/video/graphics skills, poetry, music
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Data_Security
    attributes:
      label: Data Security
      description: e.g. privacy, encryption, protection of personal data
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Open_Source
    attributes:
      label: Open Source
      description: e.g. git, open source philosophy, open source licenses
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Repair
    attributes:
      label: Repair
      description: e.g. managing repair cafes, skills on how to fix bikes, electronics etc.
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: textarea
    id: Other_Skills
    attributes:
      label: ... Any Other Skills
      description: e.g. managing repair cafes, skills on how to fix bikes, electronics etc.
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false


  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell others about yourself, your story, your expertise in some short words or several paragraphs.
    validations:
      required: true
