name: New Profile
description: Create a new profile (you can find tutorials in the wiki) 
title: "Create Profile for ..."
labels: [Profile]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out some informations about you! Great to have you as part of the LEAD network! Your data will be published on the LEAD page. Here you can find a tutorial to help you in filling out your information: [link](https://github.com/ASKnetCommunity/LEAD/wiki/Tutorial-%22New-Profile%22-(for-ASKnet-Peers)). If you already have a profile which you want to update, please use [this link](https://github.com/ASKnetCommunity/LEAD/issues/new?assignees=&labels=ChangeProfile&template=change-profile.yml&title=Change+Profile+for+...) to submit your changes. 
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "your full name"
    validations:
      required: true  
  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload an image for your profile by dragging & dropping into this textarea or clicking on the bottom of this textarea and select your image. 
    validations:
      required: true
     

  - type: markdown
    attributes:
      value: |
        ## Skills 
        What are your skills? You can specify other skills in your description text. Please provide an estimation of your skill level on a scale from 0 to 100. As a guideline: 25 = some experience, 50 = I can be a trainer / mentor in that field, 100 = I am an absolute professional. Leave the field empty (or write 0) if you don't want to mention that specific skill on your profile. 

  - type: checkboxes
    id: webbb
    attributes:
      label: > Webbb
      description: "e.g. research, using platforms, basic social media experience. Just choose one. "
      options:
        - label: none
          required: false
        - label: beginner
          required: false
        - label: intermediary
          required: false
        - label: advanced
          required: false
  - type: input
    id: web-id
    attributes:
      label: web-label
      description: "please give some form of confirmation to show you have skills in that area. That can be a certificate (give issuer, course name, date, maybe extra info), some project or product you have done (something you've built, a podcast, an event, etc.), or some other evidence / confirmation in that skill area"
      placeholder: "infos / links / etc."      
    validations:
      required: false

  - type: checkboxes
    id: soffftware
    attributes:
      label: > soffftware
      description: "e.g. installing and using different programs, basic coding skills. Just choose one. "
      options:
        - label: none
          required: false
        - label: beginner
          required: false
        - label: intermediary
          required: false
        - label: advanced
          required: false
  - type: textarea
    id: software-id
    attributes:
      label: software-label
      description: "please give some form of confirmation to show you have skills in that area. That can be a certificate (give issuer, course name, date, maybe extra info), some project or product you have done (something you've built, a podcast, an event, etc.), or some other evidence / confirmation in that skill area"
    validations:
      required: false 
  - type: input
    id: hardware-id
    attributes:
      label: Hardware-label
      description: "experience with electronic and/or mechanical devices and hardware"
      placeholder: "infos / links / etc."      
    validations:
      required: false 
  - type: input
    id: community
    attributes:
      label: Community
      description: "e.g. community building, connecting people, activism, trauma healing, gender equality awareness"
      placeholder: "0-100"
    validations:
      required: false 
  - type: input
    id: orgdev
    attributes:
      label: Organizational Development
      description: "e.g. entrepreneurship, project management, leading associations, financial literacy etc."
      placeholder: "0-100"
    validations:
      required: false 
  - type: input
    id: media-art
    attributes:
      label: Media & Art
      description: "e.g. audio/video/graphics skills, poetry, music"
      placeholder: "0-100"
    validations:
      required: false 
  - type: input
    id: datasec
    attributes:
      label: Data Security
      description: "e.g. privacy, encryption, protection of personal data"
      placeholder: "0-100"
    validations:
      required: false 
  - type: input
    id: opensource
    attributes:
      label: Open Source
      description: "e.g. git, open source philosophy, open source licenses"
      placeholder: "0-100"
    validations:
      required: false 
  - type: input
    id: repair
    attributes:
      label: Repair
      description: "e.g. managing repair cafes, skills on how to fix bikes, electronics et.c"
      placeholder: "0-100"
    validations:
      required: false 


  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell others about yourself, your story, your expertise in some short words or several paragraphs.
    validations:
      required: true
